### ISSUE TITLE
Struggling at end of Chapter 28 - no targeting or firing

### ISSUE THREAD

**Issue by leethobbit** [Apress/game-programming-unity-csharp#1]
Hello, thanks for the great book so far.  I'm pulling my hair out trying to figure out what I did wrong in Chapter 28 though.  I have checked and rechecked my scripts and the connectivity to components in Unity.  My towers never look at my enemies nor fire.  I do not see any errors or anything. I will continue to compare side by side with your code here and close this if I find the solution.  Thanks for any thoughts you can provide!

**Comment by leethobbit** [comment]
Well it's working now... the only thing I did was remove empty Start() and Update() blocks from the scripts that didn't use them.  Can leaving those in cause scripts to fail?  Thanks for the great book!!

**Comment by selcukyazarklu** [comment]
Hi, Again Chapter 28 cannot instantate the projectiles. You would better share project prepab details.
